Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml.vb
=> fix: issue #19

Plain Craft Launcher 2/Application.xaml.vb
=> 修复：webp 图片无法加载

Plain Craft Launcher 2/Application.xaml.vb, Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/Modules/Base/ModBase.vb
=> fix: 修改了部分过时文本

.github/workflows/build.yml
=> Add Support for littleskin OAuth Login

Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/My Project/AssemblyInfo.vb
=> fix: 更新相关内容

Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml, Plain Craft Launcher 2/Pages/PageOther/PageOtherTest.xaml.vb
=> feat: 清理游戏垃圾

Plain Craft Launcher 2/FormMain.xaml, Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
=> feat: 添加在标题栏上的社区版标识

Plain Craft Launcher 2/Modules/ModSecret.vb, Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb, Plain Craft Launcher 2/Pages/PageSetup/ModSetup.vb
=> fix: config read error

.github/ISSUE_TEMPLATE/bug1.yml, .github/ISSUE_TEMPLATE/bug2.yml, .github/ISSUE_TEMPLATE/bug9.yml, .github/ISSUE_TEMPLATE/ch.yml, .github/ISSUE_TEMPLATE/feature.yml
=> 修改 Issues 模板

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadInstall.xaml.vb
=> fix: text not disappear

Plain Craft Launcher 2/Modules/Base/MyBitmap.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb
=> faet: async image load

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
=> feat: resource save auto locate

Plain Craft Launcher 2/Modules/ModSecret.vb
=> fix: update replace file name incorrect

Plain Craft Launcher 2/Application.xaml.vb, Plain Craft Launcher 2/FormMain.xaml, Plain Craft Launcher 2/Modules/Base/ModBase.vb, Plain Craft Launcher 2/My Project/AssemblyInfo.vb
=> feat: Allow to open together with the official version

Plain Craft Launcher 2/FormMain.xaml.vb
=> fix: drag file not apply

Plain Craft Launcher 2/Application.xaml.vb, Plain Craft Launcher 2/Modules/Base/ModBase.vb, Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
=> Java 优先使用高性能 GPU 启动

Plain Craft Launcher 2/Modules/Base/ModBase.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionScreenshot.xaml.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
=> fix: logic error

Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
=> chore: addition msg output

Plain Craft Launcher 2/Modules/ModSecret.vb
=> fix: 深色模式 #4

Plain Craft Launcher 2/Controls/MyCard.vb, Plain Craft Launcher 2/Controls/MyHint.xaml.vb, Plain Craft Launcher 2/Modules/Minecraft/MyLocalModItem.xaml.vb, Plain Craft Launcher 2/Modules/ModSecret.vb
=> fix: 深色模式 #5

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
=> fix: button not display well

Plain Craft Launcher 2/Pages/PageLaunch/MyMsgLogin.xaml
=> fix: incorrect value

Plain Craft Launcher 2/Modules/Minecraft/ModComp.vb, Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml
fix: 会意外多次弹出同一链接的剪贴板提示
dev: ModComp 框了两个 Region
ui: 调整了资源详情页顶部的介绍 Card 边距
=> 剪贴板修复与部分 UI 调整

Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/Modules/Base/ModBase.vb, Plain Craft Launcher 2/My Project/AssemblyInfo.vb
=> bump: 2.10.0

Plain Craft Launcher 2/Pages/PageVersion/PageVersionInstall.xaml
Fix #191
按照上述帖子内的意见将版本修改处 Minecraft 项的 `返回` 改为了 `修改`
=> chore(ui): 文本优化

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompFavorites.xaml.vb
=> fix: select logic error

Plain Craft Launcher 2/Modules/Minecraft/ModLaunch.vb
=> Fix:第三方登录 Bug

.github/ISSUE_TEMPLATE/ch.yml, .github/ISSUE_TEMPLATE/feature.yml
=> feat: issue template 添加官方版引用

Plain Craft Launcher 2/Controls/MyHint.xaml.vb
=> fix: 深色模式 #7

Plain Craft Launcher 2/Application.xaml, Plain Craft Launcher 2/Modules/ModSecret.vb
=> fix: 深色模式 #9

Plain Craft Launcher 2/Pages/PageVersion/PageVersionResourcePack.xaml.vb, Plain Craft Launcher 2/Pages/PageVersion/PageVersionShader.xaml.vb
=> fix: potential exception throw

.github/workflows/build.yml
=> Revert "Fix:硬编码导致编译问题&Self-hosted Runner 不会自动清理文件导致编译失败"

Plain Craft Launcher 2/Pages/PageDownload/PageDownloadCompDetail.xaml.vb
=> fix: install function not work

Plain Craft Launcher 2/Modules/Base/ModBase.vb
Close #266 
@Pigeon0v0 下次[别瞎写类型](https://github.com/PCL-Community/PCL2-CE/blame/main/Plain%20Craft%20Launcher%202/Modules/Base/ModBase.vb#L84)……
=> fix: are u sure about that????

Plain Craft Launcher 2/Pages/PageVersion/PageVersionSetup.xaml
=> fix: 深色模式 #10

Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/Modules/Base/ModBase.vb
=> 2.10.3 360

Plain Craft Launcher 2/FormMain.xaml.vb, Plain Craft Launcher 2/Pages/PageLaunch/PageLaunchRight.xaml.vb
=> 2.10.3 -> Slow Ring

Plain Craft Launcher 2/Pages/PageVersion/PageVersionMod.xaml.vb
Close #285 
经过优化后，排序的复杂段降为 O(nlogn)
~~原来是 O(n^2) ，怎么写出来的这破代码~~
=> fix: 排序花费太多时间

Plain Craft Launcher 2/Modules/Minecraft/ModMinecraft.vb
resolves https://github.com/PCL-Community/PCL2-CE/issues/314
=> fix: treat cleanroom instances as installable mods

Plain Craft Launcher 2/Pages/PageOther/PageOtherFeedback.xaml.vb
=> perf(Feedback): 打开网页后关闭弹窗

Plain Craft Launcher 2/Application.xaml.vb, Plain Craft Launcher 2/Modules/Base/ModNet.vb
=> perf(Proxy): Modify the text of the logging

Plain Craft Launcher 2/Modules/Base/ModBase.vb
=> fix(Update): 判断是否需要更新逻辑有误
